package org.example.entity.enums;

public enum UserState {
    START_STATE,
    WAIT_FOR_NAME_STATE,
    WAIT_FOR_NUMBER_STATE,
    PRODUCT_SELECTION,
    WAIT_FOR_DECREE,
    WAIT_FOR_PHOTO_1_STATE,
    WAIT_FOR_PHOTO_2_STATE,
    GOT_FIRST_TICKET_STATE,
    GOT_ANY_TICKET_STATE,
    GOT_SECOND_TICKET_STATE,
    ADMIN_AUTHENTICATION_STATE,
    ADMIN_STATE,
    SEND_FEEDBACK,
    REMINDERS_SELECTION_OPTIONS,
    REMINDERS_SELECTION_OPTIONS_ALL,
    REMINDERS_SELECTION_OPTIONS_NOTTICKET
}
